'use strict';
function renderAll(){applySettings();renderMap();renderParts();renderMetrics();renderHistory();renderSprites();$('#summary').textContent=summary();$('#day-pill').textContent=`DAY ${state.day}`;$('#weather-pill').textContent=({clear:'☀ CLEAR',rain:'☂ RAIN',wind:'↝ WIND',heat:'▲ HEAT'}[state.weather]||state.weather);$('#people-pill').textContent=`${state.children} ${state.children===1?'CHILD':'CHILDREN'}`;$('#promise-pill').textContent=`${state.tiles.filter(t=>t.intention).length} INTENTIONS`;$('#story').textContent=state.lastStory;$('#undo').disabled=!undoStack.length;$('#redo').disabled=!redoStack.length;$('#diagnostics').textContent=`App ready · ${state.tiles.length} map cells · ${state.history.length} anonymous events · ${state.sprites.length} custom entities · storage ${save()?'available':'memory only'}.`;}
function renderMap(){const map=$('#map');map.innerHTML='';state.tiles.forEach((t,i)=>{const b=document.createElement('button');b.className=`tile ${t.terrain}`;b.type='button';b.dataset.i=i;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${t.terrain} at column ${t.x+1}, row ${t.y+1}${t.structure?', '+parts[t.structure]?.label:''}${t.intention?', intention: '+intentionDefs[t.intention]:''}`);if((selectedPart&&terrainValid(t,selectedPart))||(intentMode)||(releaseSprite))b.classList.add('valid');if(t.structure)b.innerHTML+=svg(t.structure);if(t.entity)b.innerHTML+=t.entity.custom?pixelSvg(t.entity.pixels,t.entity.color,true):svg('entity',t.entity.color);if(t.intention)b.innerHTML+=`<span class="marker" title="${intentionDefs[t.intention]}">${t.intention[0].toUpperCase()}</span>`;b.addEventListener('click',()=>tileTap(i));map.appendChild(b)});}
function tileTap(i){const t=state.tiles[i];if(releaseSprite){snapshot();t.entity={custom:true,pixels:releaseSprite.pixels,color:releaseSprite.color,name:releaseSprite.name,behavior:releaseSprite.behavior};state.history.unshift({day:state.day,text:`A new citizen called ${releaseSprite.name} entered the city.`});state.lastStory=`${releaseSprite.name} arrived and began to ${releaseSprite.behavior.replace('garden','seek gardens').replace('water','follow water').replace('repair','look for repairs').replace('gather','visit gatherings')}.`;releaseSprite=null;save();renderAll();showView('city');toast('Custom citizen released into the city.');return}
 if(intentMode){snapshot();t.intention=intentMode;state.history.unshift({day:state.day,text:`A visitor left the intention “${intentionDefs[intentMode]}” at ${t.x+1},${t.y+1}.`});state.lastStory=`Someone asked future visitors to “${intentionDefs[intentMode].toLowerCase()}.” The city will remember even after they leave.`;intentMode=null;save();renderAll();toast('The intention will remain for future visitors.');return}
 if(!selectedPart){mapMessage(t);return}if(!terrainValid(t,selectedPart)){toast('That piece cannot go there. Lit places are valid.');return}const p=parts[selectedPart];if(p.joint&&state.children<2){toast('This bridge needs a second child. Tap “Another child joins.”');return}if((state.inventory[selectedPart]||0)<1){toast('No pieces of that kind remain.');return}
 snapshot();t.structure=selectedPart;state.inventory[selectedPart]--;Object.entries(p.delta).forEach(([k,v])=>state.metrics[k]=clamp(state.metrics[k]+v,0,12));const where=`column ${t.x+1}, row ${t.y+1}`;state.history.unshift({day:state.day,text:`Visitors placed a ${p.label.toLowerCase()} at ${where}.`});state.lastStory=placementStory(selectedPart,t);selectedPart=null;save();renderAll();toast('Placed. Watch the city systems change.');}
function placementStory(type,t){const s={path:'A new route opened. Nearby residents can meet, but a strip of habitat became hard ground.',home:'A new neighbor has shelter. The city must now share its water and routes with another home.',garden:'Flowers opened and pollinators arrived. The garden also began drawing from the shared water.',bridge:'Two children coordinated a crossing. The districts connect, but wetland creatures lost a quiet stretch of water.',shelter:'A public shelter opened. Rain and heat now affect fewer residents.',wetland:'Water slowed among new reeds. Frogs returned and the western edge can hold more rain.',stage:'A gathering place appeared. The city may now produce assemblies, music, or arguments—the civic trinity.',repair:'A strained place was patched. The repair remains visible instead of pretending nothing happened.'};return s[type]||'The city changed.'}
function mapMessage(t){let text=`${t.terrain} at ${t.x+1},${t.y+1}.`;if(t.structure)text+=` It contains a ${parts[t.structure]?.label.toLowerCase()}.`;if(t.intention)text+=` Earlier visitors asked: ${intentionDefs[t.intention]}.`;$('#map-note').textContent='◆ '+text;}
function renderParts(){const box=$('#parts');box.innerHTML='';Object.entries(parts).filter(([k,p])=>selectedFilter==='all'||p.cat===selectedFilter).forEach(([k,p])=>{const b=document.createElement('button');b.className='part-card'+(selectedPart===k?' active':'');b.type='button';b.innerHTML=`<span class="count">${state.inventory[k]||0}</span><span class="part-icon">${svg(k)}</span><span><strong>${p.label}</strong><small>${p.desc}${p.joint?' Requires two children.':''}</small></span>`;b.disabled=(state.inventory[k]||0)<1;b.addEventListener('click',()=>{selectedPart=selectedPart===k?null:k;intentMode=null;releaseSprite=null;renderAll();$('#map-note').textContent=selectedPart?`◆ ${p.label} selected. Tap a lit place.`:'◆ Pick a loose part. Valid places will light up.'});box.appendChild(b)});}
function renderMetrics(){for(const k of ['water','move','shelter','habitat'])$('#m-'+k).textContent=state.metrics[k]}
