'use strict';
function respond(){snapshot();state.day++;const d=state.day%4;state.weather=['clear','rain','wind','heat'][d];let story='The city observed what remained.';if(state.weather==='rain'){state.metrics.water=clamp(state.metrics.water+2,0,12);story='Rain filled channels and low ground. Wetlands absorbed some of it; hard paths sent the rest downhill.'}if(state.weather==='heat'){state.metrics.water=clamp(state.metrics.water-2,0,12);story='Heat dried the western edge. Gardens without nearby water began to droop, while shelters became more valuable.'}if(state.weather==='wind'){story='Wind crossed the high ground. Gathering places emptied, but seeds moved toward open habitat.';state.metrics.habitat=clamp(state.metrics.habitat+1,0,12)}if(state.metrics.move>=7&&state.tiles.some(t=>t.structure==='stage'))story+=' Connected routes produced a market at the commons.';if(state.metrics.habitat>=8)story+=' Frogs and pollinators established a new route through the city.';
 moveEntities();state.lastStory=story;state.history.unshift({day:state.day,text:story});save();renderAll();toast(`Day ${state.day}: ${state.weather}.`)}
function moveEntities(){const ents=state.tiles.map((t,i)=>t.entity?i:-1).filter(i=>i>=0);ents.forEach(i=>{const e=state.tiles[i].entity,choices=state.tiles.filter(t=>!t.entity&&((e.behavior==='water'&&t.terrain==='water')||(e.behavior==='garden'&&t.structure==='garden')||(e.behavior==='repair'&&t.intention)||(e.behavior==='gather'&&t.structure==='stage')||e.behavior==='wander'));if(choices.length){state.tiles[i].entity=null;choices[(state.day+i)%choices.length].entity=e}})}
function leaveIntention(){const buttons=Object.entries(intentionDefs).map(([k,v])=>`<button data-int="${k}">${v}</button>`).join('');openModal('Leave something for the next child',`<p class="muted">Choose an intention, then tap any place in the city. It is anonymous and persistent.</p><div class="choices">${buttons}</div>`);$$('[data-int]').forEach(b=>b.onclick=()=>{intentMode=b.dataset.int;selectedPart=null;closeModal();showView('city');renderAll();$('#map-note').textContent=`◆ “${intentionDefs[intentMode]}” selected. Tap a place.`})}
function renderHistory(){const h=$('#history');h.innerHTML=state.history.length?state.history.map(e=>`<article><time>DAY ${e.day}</time><br>${escapeHtml(e.text)}</article>`).join(''):'<div class="empty">The city has no memory yet.</div>'}
function openModal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;$('#modal-backdrop').hidden=false}
function closeModal(){$('#modal-backdrop').hidden=true}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2600)}
function showView(name){$$('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);$$('nav button').forEach(b=>b.setAttribute('aria-selected',b.dataset.view===name?'true':'false'));window.scrollTo({top:0,behavior:state.settings.motion?'auto':'smooth'})}
function applySettings(){document.body.classList.toggle('high-contrast',!!state.settings.contrast);document.body.classList.toggle('reduce-motion',!!state.settings.motion);document.body.classList.toggle('large',!!state.settings.large)}
