'use strict';
function pixelSvg(pixels,color,entity=false){let rects='';pixels.forEach((c,i)=>{if(c)rects+=`<rect x="${i%12}" y="${Math.floor(i/12)}" width="1" height="1" fill="${c}"/>`});return `<svg ${entity?'class="sprite entity"':''} viewBox="0 0 12 12" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`}
function renderEditor(){const e=$('#pixel-editor');e.innerHTML='';spritePixels.forEach((c,i)=>{const b=document.createElement('button');b.className='px'+(c?' on':'');b.style.setProperty('--paint',c||'transparent');b.dataset.i=i;b.setAttribute('aria-label',`Pixel ${i%12+1}, ${Math.floor(i/12)+1}`);const apply=()=>{spritePixels[i]=tool==='erase'?'':paint;renderEditor();renderPreview()};b.onpointerdown=ev=>{drawing=true;b.setPointerCapture?.(ev.pointerId);apply()};b.onpointerenter=()=>{if(drawing)apply()};e.appendChild(b)});}
function renderPalette(){const p=$('#palette');p.innerHTML='';colors.forEach(c=>{const b=document.createElement('button');b.className='swatch'+(paint===c?' active':'');b.style.background=c;b.setAttribute('aria-label',`Use ${c}`);b.onclick=()=>{paint=c;renderPalette()};p.appendChild(b)})}
function renderPreview(){$('#sprite-preview').innerHTML=pixelSvg(spritePixels,paint,false)}
function randomName(){const a=['Bright','Quiet','Mossy','Little','Copper','Rain','Sunny','Kind','Wild','Brave'],b=['Walker','Builder','Keeper','Mapper','Listener','Mender','Singer','Gardener','Courier','Dreamer'];return a[(state.day+state.sprites.length*3)%a.length]+' '+b[(state.history.length+state.sprites.length)%b.length]}
function newName(){const n=randomName();$('#sprite-name').textContent=n}
function saveSprite(){if(!spritePixels.some(Boolean)){toast('Draw at least one pixel first.');return}const s={id:Date.now(),name:$('#sprite-name').textContent,behavior:$('#behavior').value,social:$('#social').value,pixels:[...spritePixels],color:paint};state.sprites.push(s);releaseSprite=s;state.history.unshift({day:state.day,text:`A visitor designed ${s.name}, ready to enter the city.`});save();renderSprites();renderMap();showView('city');$('#map-note').textContent=`◆ ${s.name} is ready. Tap a lit place to release them.`;toast('Sprite saved. Choose where it enters the city.')}
function renderSprites(){const box=$('#saved-sprites');if(!box)return;box.innerHTML=state.sprites.length?state.sprites.map(s=>`<article><strong>${escapeHtml(s.name)}</strong><br>${escapeHtml(s.behavior)} · ${escapeHtml(s.social)}</article>`).join(''):'<div class="empty">No custom entities yet.</div>'}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
