import type { LanternState } from "./types";

export const initialState: LanternState = {
  revision: 18,
  publishedAt: "Today, 9:12 AM",
  nextScheduledEvent: "Test Message 1 at 10:00 AM",
  lastBackup: "Today, 8:45 AM",
  donors: [
    { id: "test-family-1", name: "Test Family Alpha", tier: "Founder", category: "Family", active: true, since: "2026", note: "Test record — family/founder", tags: ["(test)", "Supporter", "Education", "Custom icon"], customIconImage: "/assets/donor-icons/star.png", groupId: "group-founders", displayIds: ["display-1", "display-2"] },
    { id: "test-family-2", name: "Test Family Beta", tier: "Champion", category: "Family", active: true, since: "2026", note: "Test record — family/champion", tags: ["(test)", "Community", "Annual", "Custom icon"], customIconImage: "/assets/donor-icons/toy-soldier.png", groupId: "group-community", displayIds: ["display-1", "display-2"] },
    { id: "test-family-3", name: "Test Family Gamma", tier: "Patron", category: "Family", active: true, since: "2026", note: "Test record — family/patron", tags: ["(test)", "Legacy"], groupId: "group-programs", displayIds: ["display-1", "display-2"] },
    { id: "test-corporate-1", name: "Test Company Alpha", tier: "Founder", category: "Corporate", active: true, since: "2026", note: "Test record — corporate/founder", tags: ["(test)", "Annual", "Education"], groupId: "group-founders", displayIds: ["display-1", "display-2"] },
    { id: "test-corporate-2", name: "Test Company Beta", tier: "Champion", category: "Corporate", active: true, since: "2026", note: "Test record — corporate/champion", tags: ["(test)", "Supporter", "Community"], groupId: "group-community", displayIds: ["display-1", "display-2"] },
    { id: "test-corporate-3", name: "Test Company Gamma", tier: "Friend", category: "Corporate", active: true, since: "2026", note: "Test record — corporate/friend", tags: ["(test)", "Legacy", "Annual"], groupId: "group-programs", displayIds: ["display-1", "display-2"] },
    { id: "test-community-1", name: "Test Community Alpha", tier: "Founder", category: "Community", active: true, since: "2026", note: "Test record — community/founder", tags: ["(test)", "Community", "Education"], groupId: "group-founders", displayIds: ["display-1", "display-2"] },
    { id: "test-community-2", name: "Test Community Beta", tier: "Patron", category: "Community", active: true, since: "2026", note: "Test record — community/patron", tags: ["(test)", "Supporter", "Annual"], groupId: "group-community", displayIds: ["display-1", "display-2"] },
    { id: "test-community-3", name: "Test Community Gamma", tier: "Friend", category: "Community", active: true, since: "2026", note: "Test record — community/friend", tags: ["(test)", "Legacy", "Community"], groupId: "group-programs", displayIds: ["display-1", "display-2"] },
    { id: "test-legacy-1", name: "Test Legacy Alpha", tier: "Champion", category: "Legacy", active: true, since: "2026", note: "Test record — legacy/champion", tags: ["(test)", "Legacy", "Education"], groupId: "group-founders", displayIds: ["display-1", "display-2"] },
    { id: "test-legacy-2", name: "Test Legacy Beta", tier: "Patron", category: "Legacy", active: true, since: "2026", note: "Test record — legacy/patron", tags: ["(test)", "Supporter", "Community", "Annual"], groupId: "group-community", displayIds: ["display-1", "display-2"] },
    { id: "test-legacy-3", name: "Test Legacy Gamma", tier: "Friend", category: "Legacy", active: true, since: "2026", note: "Test record — legacy/friend", tags: ["(test)", "Supporter", "Legacy"], groupId: "group-programs", displayIds: ["display-1", "display-2"] }
  ],
  donorGroups: [
    { id: "group-founders", name: "Founding supporters", color: "#f2c46d" },
    { id: "group-community", name: "Community partners", color: "#55c7bf" },
    { id: "group-programs", name: "Program sponsors", color: "#f07b5f" }
  ],
  recognitionSettings: {
    tiers: ["Founder", "Champion", "Patron", "Friend"],
    categories: ["Family", "Corporate", "Community", "Legacy"],
    tags: ["(test)", "Supporter", "Education", "Community", "Annual", "Legacy", "Custom icon"],
    appearance: "dark"
  },
  theme: {
    material: "Walnut",
    finish: "Satin",
    lettering: "Engraved",
    trim: "Brass",
    warmth: 62,
    grain: 58,
    letteringDepth: 44,
    shadowSoftness: 64,
    motion: 38
  },
  board: {
    presetName: "Museum Classic - Reference Layout",
    visualStyle: "chalkboard",
    donorColumns: 2,
    portraitHeading: "THANK YOU",
    portraitSubtitle: "OUR GENEROUS DONORS",
    portraitDescription: "TOGETHER, WE MAKE A DIFFERENCE.",
    portraitFooter: "TOGETHER, WE MAKE A DIFFERENCE.",
    landscapeHeadingPrimary: "MAKING WONDER",
    landscapeHeadingAccent: "POSSIBLE",
    landscapeSubtitle: "THANK YOU TO OUR INCREDIBLE SUPPORTERS",
    storyEyebrow: "FEATURED STORY",
    storyTitle: "Wonder grows here.",
    storyBody: "Your support builds hands-on learning, sparks curiosity, and creates a brighter future.",
    storyImageUrl: "",
    hoursLabel: "TODAY'S HOURS",
    hoursValue: "10:00 AM - 5:00 PM",
    impactLines: ["YOU HELP", "IMAGINATION", "COME TO LIFE"],
    theaterLabel: "THEATER SHOW",
    theaterValue: "Starts in 35 min",
    membershipLabel: "MEMBERSHIP",
    membershipValue: "Make a lasting impact",
    socialLabel: "FOLLOW US",
    socialValue: "Stay connected",
    footerVisibility: {
      portraitHours: true,
      portraitImpact: true,
      landscapeTheater: true,
      landscapeHours: true,
      landscapeMembership: true,
      landscapeSocial: true
    }
  },
  boardPrograms: [
    {
      id: "board-classic",
      name: "Our Generous Donors",
      orientation: "Portrait",
      heading: "THANK YOU",
      subtitle: "OUR GENEROUS DONORS",
      description: "TOGETHER, WE MAKE A DIFFERENCE.",
      footer: "TOGETHER, WE MAKE A DIFFERENCE.",
      columns: 2,
      donorIds: ["test-family-1", "test-family-2", "test-family-3", "test-corporate-1", "test-corporate-2", "test-corporate-3", "test-community-1", "test-community-2", "test-community-3", "test-legacy-1", "test-legacy-2", "test-legacy-3"],
      active: true
    },
    {
      id: "board-spotlight",
      name: "Community Spotlight",
      orientation: "Landscape",
      heading: "THANK YOU",
      subtitle: "COMMUNITY PARTNERS",
      description: "YOUR SUPPORT BUILDS A BRIGHTER FUTURE.",
      footer: "WITH GRATITUDE TO OUR COMMUNITY.",
      columns: 1,
      donorIds: ["test-family-1", "test-family-2", "test-family-3", "test-corporate-1", "test-corporate-2", "test-corporate-3", "test-community-1", "test-community-2", "test-community-3", "test-legacy-1", "test-legacy-2", "test-legacy-3"],
      active: true
    }
  ],
  schedules: [
    { id: "schedule-portrait-board", name: "Portrait board · Display 1", target: "display-1", boardId: "board-classic", contentType: "board", days: [0, 3, 4, 5, 6], recurrence: "weekly", startTime: "07:00", endTime: "18:00", color: "#5f55bd", active: true },
    { id: "schedule-landscape-board", name: "Landscape board · Display 2", target: "display-2", boardId: "board-spotlight", contentType: "board", days: [0, 3, 4, 5, 6], recurrence: "weekly", startTime: "07:00", endTime: "18:00", color: "#218ba2", active: true },
    { id: "schedule-test-message-1", name: "Test Message 1", target: "display-1", boardId: "board-classic", contentType: "announcement", announcementId: "announcement-test-1", days: [0, 3, 4, 5, 6], recurrence: "weekly", startTime: "10:00", endTime: "10:10", color: "#a95777", active: true },
    { id: "schedule-test-message-2", name: "Test Message 2", target: "display-1", boardId: "board-classic", contentType: "announcement", announcementId: "announcement-test-2", days: [0, 3, 4, 5, 6], recurrence: "weekly", startTime: "13:00", endTime: "13:10", color: "#218ba2", active: true },
    { id: "schedule-test-message-3", name: "Test Message 3", target: "display-1", boardId: "board-classic", contentType: "announcement", announcementId: "announcement-test-3", days: [0, 3, 4, 5, 6], recurrence: "weekly", startTime: "15:00", endTime: "15:10", color: "#956330", active: true }
  ],
  savedAnnouncements: [
    {
      id: "announcement-test-1",
      title: "Test Message 1",
      message: "Test message 1",
      target: "display-1",
      priority: "Normal",
      style: "Ribbon",
      durationMinutes: 10,
      timerStyle: "off",
      timerPosition: "announcement-right",
      timerAccentColor: "#6847e8",
      timerTrackColor: "#e8e0d0",
      finishSfx: "off",
      sfxVolume: 70,
      character: "off"
    },
    {
      id: "announcement-test-2",
      title: "Test Message 2",
      message: "Test message 2",
      target: "display-1",
      priority: "Normal",
      style: "Ribbon",
      durationMinutes: 10,
      timerStyle: "off",
      timerPosition: "announcement-right",
      timerAccentColor: "#6847e8",
      timerTrackColor: "#e8e0d0",
      finishSfx: "off",
      sfxVolume: 70,
      character: "off"
    },
    {
      id: "announcement-test-3",
      title: "Test Message 3",
      message: "Test message 3",
      target: "display-1",
      priority: "Normal",
      style: "Ribbon",
      durationMinutes: 10,
      timerStyle: "off",
      timerPosition: "announcement-right",
      timerAccentColor: "#6847e8",
      timerTrackColor: "#e8e0d0",
      finishSfx: "off",
      sfxVolume: 70,
      character: "off"
    },
    {
      id: "a-001",
      title: "Story Time",
      message: "Wonder Lab story time begins at 2:30 PM.",
      target: "display-2",
      priority: "Normal",
      style: "Ribbon",
      durationMinutes: 20,
      timerStyle: "off",
      timerPosition: "announcement-right",
      timerAccentColor: "#6847e8",
      timerTrackColor: "#e8e0d0",
      finishSfx: "off",
      sfxVolume: 70,
      character: "off"
    }
  ],
  announcement: {
    id: "a-001",
    title: "Story Time",
    message: "Wonder Lab story time begins at 2:30 PM.",
    target: "display-2",
    priority: "Normal",
    style: "Ribbon",
    active: false,
    durationMinutes: 20,
    timerStyle: "off",
    timerPosition: "announcement-right",
    timerAccentColor: "#6847e8",
    timerTrackColor: "#e8e0d0",
    finishSfx: "off",
    sfxVolume: 70,
    character: "off",
    startSoundUrl: undefined,
    endSoundUrl: undefined
  },
  live: {
    active: false,
    target: "display-1",
    title: "Title of Broadcast",
    lowerThird: "Sub-header text",
    titlePosition: { x: 26, y: 18 },
    lowerThirdPosition: { x: 38, y: 24 },
    backgroundMode: "board",
    backgroundColor: "#07111e",
    backgroundImage: undefined,
    panelColor: "#050d17",
    frameBorderColor: "#5fe0eb",
    frameBorderWidth: 0,
    usingCamera: true,
    source: "camera",
    frame: { x: 24, y: 13, width: 65, height: 80, crop: { scale: 1.4, x: 6, y: -34 }, maskShape: "rectangle", rotation: -1, mirrorX: false },
    chromaKey: { enabled: false, color: "#18a558", similarity: 0.34, smoothness: 0.12, spill: 0.18 },
    effects: { background: "remove", blur: 18, segmentationThreshold: 0.42, segmentationFeather: 0.18, accessory: "none", faceTracking: false, puppetPreview: false }
  },
  screens: {
    "display-1": {
      id: "display-1",
      label: "Display 1",
      orientation: "Portrait",
      resolution: "1080 x 1920",
      assignment: "Test window",
      style: "donor-wall",
      backgroundCrop: { scale: 1, x: 0, y: 0 },
      layoutScale: 100,
      brightness: 72,
      currentRevision: 18,
      renderer: "WebGL2",
      quality: "Balanced",
      fps: 0,
      status: "offline",
      enabled: true,
      boardProgramId: "board-classic",
      donorIds: [],
      customHeading: "THANK YOU",
      customSubheading: "OUR GENEROUS DONORS",
      fontFamily: "Montserrat",
      nameSize: 30,
      columns: 1,
      donorScrollEnabled: false,
      donorScrollSpeed: 4,
      particleAnimationEnabled: false,
      particleDriftDirection: "natural",
      particleDriftSpeed: 4,
      particleGravity: 3,
      showIcons: false,
      donorIconStyle: "circle",
      donorIconPlacement: "left",
      showSubtext: false,
    },
    "display-2": {
      id: "display-2",
      label: "Display 2",
      orientation: "Landscape",
      resolution: "1920 x 1080",
      assignment: "Test window",
      style: "donor-wall",
      backgroundCrop: { scale: 1, x: 0, y: 0 },
      layoutScale: 100,
      brightness: 72,
      currentRevision: 18,
      renderer: "WebGL2",
      quality: "Showcase",
      fps: 0,
      status: "offline",
      enabled: true,
      boardProgramId: "board-spotlight",
      donorIds: [],
      customHeading: "THANK YOU",
      customSubheading: "OUR GENEROUS DONORS",
      fontFamily: "Montserrat",
      nameSize: 28,
      columns: 2,
      donorScrollEnabled: false,
      donorScrollSpeed: 4,
      particleAnimationEnabled: false,
      particleDriftDirection: "natural",
      particleDriftSpeed: 4,
      particleGravity: 3,
      showIcons: false,
      donorIconStyle: "circle",
      donorIconPlacement: "left",
      showSubtext: false,
    }
  },
  revisions: [
    { id: 18, note: "Walnut donor wall with story-time schedule", author: "Lantern Host", publishedAt: "Today, 9:12 AM", portraitReady: true, landscapeReady: true },
    { id: 17, note: "Added July donor cohort", author: "Felix", publishedAt: "Yesterday, 4:08 PM", portraitReady: true, landscapeReady: true },
    { id: 16, note: "Reduced portrait animation during morning arrivals", author: "Museum Ops", publishedAt: "Jul 8, 11:30 AM", portraitReady: true, landscapeReady: true }
  ]
};
